#' Vancouver Parking Meters
#'
#' This dataset contains information on the rates and time limits for parking meters in Vancouver. Information is shown for entire block faces rather than for individual meters. Data in the portal is updated weekly.
#'
#' @source <https://opendata.vancouver.ca/explore/dataset/parking-meters/information/>, downloaded 2020-05-06
#' @format A data frame with columns:
#' \describe{
#'  \item{meter_head}{Meter head type.}
#'  \item{r_mf_9a_6p}{Rate for Mon-Fri 9AM to 6PM.}
#'  \item{r_mf_6p_10}{Rate for Mon-Fri 6PM to 10PM.}
#'  \item{r_sa_9a_6p}{Rate for Sat 9AM to 6PM.}
#'  \item{r_sa_6p_10}{Rate for Sat 6PM to 10PM.}
#'  \item{r_su_9a_6p}{Rate for Sun 9AM to 6PM.}
#'  \item{r_su_6p_10}{Rate for Sun 6PM to 10PM.}
#'  \item{rate_misc}{Miscellaneous rate information.}
#'  \item{time_in_effect}{Times that meter is in effect.}
#'  \item{t_mf_9a_6p}{Time limit for Mon-Fri 9AM to 6PM.}
#'  \item{t_mf_6p_10}{Time limit for Mon-Fri 6PM to 10PM.}
#'  \item{t_sa_9a_6p}{Time limit for Sat 9AM to 6PM.}
#'  \item{t_sa_6p_10}{Time limit for Sat 6PM to 10PM.}
#'  \item{t_su_9a_6p}{Time limit for Sun 9AM to 6PM.}
#'  \item{t_su_6p_10}{Time limit for Sun 6PM to 10PM.}
#'  \item{time_misc}{Miscellaneous time limit information.}
#'  \item{credit_card}{Does the meter have credit card functionality?}
#'  \item{pay_phone}{Pay by Phone number.}
#'  \item{longitude}{Longitude coordinate.}
#'  \item{latitude}{Latitude coordinate.}
#'  \item{geo_local_area}{The local area where the meter is found, derived from meter's coordinates.}
#'  \item{meter_id}{Unique identifier generated by the system.}
#' }
#' @examples
#' parking_meters
#'
#' head(parking_meters)
#' summary(parking_meters)

"parking_meters"
